import { c as create_ssr_component, v as validate_component, e as escape } from "../../chunks/ssr.js";
/* empty css                  */
import { G as Gralypho } from "../../chunks/Gralypho.js";
const css$1 = {
  code: ".footer.svelte-hnxtbh.svelte-hnxtbh{display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%;font-size:16px;background-color:var(--primary);color:white;font-family:epilogue;gap:0px}.footer.svelte-hnxtbh h1.svelte-hnxtbh{margin-top:30px;font-family:'Dosis';font-weight:400;font-size:0.9rem;color:white;text-align:center;margin-bottom:50px}.wrapper-gralypho.svelte-hnxtbh.svelte-hnxtbh{display:flex;align-items:center;justify-content:center;margin:0 auto;margin-top:30px;height:auto;padding:10px}.wrapper-contactez.svelte-hnxtbh.svelte-hnxtbh{display:flex;flex-direction:row;align-items:center;justify-content:center;text-align:center;border-radius:0px;padding:40px;gap:10px;margin-top:30px;margin-bottom:20px}.contact.svelte-hnxtbh.svelte-hnxtbh{text-decoration:none;border:none;color:rgb(255, 255, 255);font-weight:200;font-size:1rem;font-family:poppins;width:60px;height:60px;transform:rotate(0deg);transition:0.2s ease-in-out;padding:50px;background-color:rgb(116, 1, 1);border-radius:40px 30px 4px 30px;box-shadow:0px 0px 10px rgba(0, 0, 0, 0.331);display:flex;align-items:center;justify-content:center;flex-direction:column;text-align:center;gap:10px}.contact.svelte-hnxtbh.svelte-hnxtbh:hover{animation:svelte-hnxtbh-bounce 0.4s ease-in-out;font-weight:800}a.svelte-hnxtbh.svelte-hnxtbh{color:var(--bleuAcier);font-size:1.5rem;margin:0 0px;transition:0.4s ease-in-out}.icon.svelte-hnxtbh.svelte-hnxtbh{color:var(--white);font-size:1.5rem}.gralypho.svelte-hnxtbh.svelte-hnxtbh{display:flex;flex-direction:column;align-items:center;justify-content:center}.anim.svelte-hnxtbh.svelte-hnxtbh:hover{animation:svelte-hnxtbh-bounce 0.4s ease-in-out}@keyframes svelte-hnxtbh-bounce{0%{transform:scale(1) translateY(-2px)}25%{transform:scale(1) translateY(3px)}50%{transform:scale(1) translateY(-1px)}75%{transform:scale(1) translateY(2px)}100%{transform:scale(1) translateY(0)}}.wrapper-media.svelte-hnxtbh.svelte-hnxtbh{display:flex;gap:20px;padding:20px}.reseaux.svelte-hnxtbh.svelte-hnxtbh{display:flex;flex-direction:column;align-items:center;justify-content:center;color:var(--blue);font-weight:800;gap:5px}.size.svelte-hnxtbh.svelte-hnxtbh{font-size:2.5rem}.reseaux.svelte-hnxtbh p.svelte-hnxtbh{color:var(--primary);font-size:0.5rem;font-weight:200}.additionnal-link.svelte-hnxtbh.svelte-hnxtbh{text-decoration:none;color:rgb(128, 128, 169);font-size:0.6rem;font-weight:200;margin-top:-20px}@media screen and (max-width: 768px){.contact.svelte-hnxtbh.svelte-hnxtbh{font-size:0.6rem;padding:30px;height:80px}.icon.svelte-hnxtbh.svelte-hnxtbh{font-size:1.3rem}.wrapper-media.svelte-hnxtbh.svelte-hnxtbh{display:flex;gap:20px}}",
  map: null
};
const Footer = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let Year;
  $$result.css.add(css$1);
  return `<footer class="footer svelte-hnxtbh"><div class="wrapper-contactez svelte-hnxtbh" data-svelte-h="svelte-f7cf8h"><a href="mailto:gralypho@gmail.com " class="contact svelte-hnxtbh" target="_blank"><i class="fa-regular fa-envelope icon svelte-hnxtbh"></i> <p>Mail</p></a> <a href="tel:0672901614" class="contact svelte-hnxtbh" target="_blank"><i class="fa-solid fa-phone-volume icon svelte-hnxtbh"></i> <p>Tel</p></a> <a href="https://koalendar.com/e/premier-rv-gratuit-avec-gralypho" class="contact svelte-hnxtbh" target="_blank"><i class="fa-solid fa-mug-hot icon svelte-hnxtbh"></i> <p>RV</p></a> <a href="https://fabienmarceau.com/gralyphoPhotography/index.html" class="contact svelte-hnxtbh" target="_blank"><i class="fa-solid fa-camera icon svelte-hnxtbh"></i> <p>Photo</p></a></div> <div class="wrapper-media svelte-hnxtbh" data-svelte-h="svelte-ymcszs"><a class="reseaux  svelte-hnxtbh" href="https://www.facebook.com/profile.php?id=61556314663680" target="_blank"><p class="svelte-hnxtbh">Facebook</p> <i class="fa-brands fa-square-facebook anim icon size svelte-hnxtbh"></i></a> <a class="reseaux svelte-hnxtbh" href="https://twitter.com/home?lang=fr" target="_blank"><p class="svelte-hnxtbh">X</p> <i class="fa-brands fa-square-twitter anim icon size svelte-hnxtbh"></i></a> <a class="reseaux  svelte-hnxtbh" href="https://www.instagram.com/" target="_blank"><p class="svelte-hnxtbh">instagram</p> <i class="fa-brands fa-square-instagram anim icon size svelte-hnxtbh"></i></a> </div> <div class="wrapper-gralypho svelte-hnxtbh"><div class="gralypho svelte-hnxtbh">${validate_component(Gralypho, "Gralypho").$$render($$result, {}, {}, {})} <h1 class="svelte-hnxtbh">© ${escape(Year)} GRALYPHO. <br> Tous droits réservés.</h1> <a href="https://www.jesuisnumerique.fr" class="additionnal-link svelte-hnxtbh" data-svelte-h="svelte-1o0oppe">Annuaire jesuisnumérique</a></div></div> </footer>`;
});
const css = {
  code: "main.svelte-1kei2hn{background-color:white;overflow:hidden;height:auto;scroll-behavior:smooth}",
  map: null
};
const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<main class="svelte-1kei2hn">${slots.default ? slots.default({}) : ``} <div id="footer">${validate_component(Footer, "Footer").$$render($$result, {}, {}, {})}</div> </main>`;
});
export {
  Layout as default
};
