import { c as create_ssr_component, v as validate_component } from "../../../chunks/ssr.js";
import { F as FaqLink } from "../../../chunks/FaqLink.js";
import { H as Header } from "../../../chunks/Header.js";
import { B as ButtonCTA } from "../../../chunks/ButtonCTA.js";
const css = {
  code: ".container.svelte-1yqlmgk{height:100%}.wrapper__text.svelte-1yqlmgk{display:flex;flex-direction:column;justify-content:center;align-items:center;width:80%;margin:0 auto}.title.svelte-1yqlmgk{font-family:var(--Geologica);font-size:var(--l);color:var(--primary);font-weight:900;margin-bottom:10px;letter-spacing:-1px;text-align:center;line-height:35px;margin-top:50px}.subtitle.svelte-1yqlmgk{font-family:var(--Geologica);font-size:1.5rem;color:var(--primary);font-weight:500;letter-spacing:-1px;text-align:center;line-height:40px;margin-top:30px;padding:25px}.subtitle__h3.svelte-1yqlmgk{font-family:var(--Geologica);font-size:var(--m);color:var(--primary);font-weight:700;letter-spacing:-1px;text-align:center;margin-top:100px}.paragraph.svelte-1yqlmgk{font-family:var(--Poppins);font-size:var(--m);color:var(--primary);font-weight:300;letter-spacing:-0.02em;text-align:center;align-self:center;padding:20px}.wrapper__img.svelte-1yqlmgk{margin-top:50px;display:flex;justify-content:center;align-items:center}.img.svelte-1yqlmgk{width:80%;margin:0 auto}@media screen and (max-width: 768px){.img.svelte-1yqlmgk{height:200px;margin-top:20px}.wrapper__text.svelte-1yqlmgk{width:90%;height:100%}}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${validate_component(Header, "Header").$$render($$result, {}, {}, {})} <div class="container svelte-1yqlmgk"><h1 class="title svelte-1yqlmgk" data-svelte-h="svelte-1yi3f4s">Création de site internet et d&#39;applications PWA.</h1> <div class="wrapper__img svelte-1yqlmgk" data-svelte-h="svelte-1dpgq5z"><img class="img svelte-1yqlmgk" src="https://images.pexels.com/photos/8430273/pexels-photo-8430273.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Lyon"></div> <div class="wrapper__text svelte-1yqlmgk"><h2 class="subtitle svelte-1yqlmgk" data-svelte-h="svelte-a24uyt">Comment créer un site internet ?</h2> <h3 class="subtitle__h3 svelte-1yqlmgk" data-svelte-h="svelte-1tbtinc">CMS ? Code ? Hybride ?</h3> <p class="paragraph svelte-1yqlmgk" data-svelte-h="svelte-1jg1ffu">Pour créer un site internet rapidement et très facilement, il y a bien sûr Wordpress ou Wix. 
            <br>. Mais attention, il y a une différence foncdamentale entre l&#39;affichage de quelques pages html sur le web et un &quot;vrai site internet&quot;, référencé, dynamique et qui puisse convertir des clients.
            <br> . Un site codé en dur, avec un framework comme Svelte, React ou Angular, vous permettra de créer un site internet sur mesure, qui répondra exactement à vos besoins.
            <br>. Un site codé pour le front et branché à un CMS headless représente une solution efficace et hyper rapide que nous apprécions particulièrement.</p> <h3 class="subtitle__h3 svelte-1yqlmgk" data-svelte-h="svelte-1uoi8x1">A qui faire appel pour créer son site internet ?</h3> <p class="paragraph svelte-1yqlmgk" data-svelte-h="svelte-h2xjwt">Le mieux est de passer par un Webmaster, un développeur Web ou une agence Web. Ceux-ci seront de bons conseils, à l&#39;écoute de vos besoins pour vous répsenter des solutiosn digitales adaptées à vos besoins.</p> <h3 class="subtitle__h3 svelte-1yqlmgk" data-svelte-h="svelte-37k1nk">Vous avez un projet de site internet ?</h3> <p class="paragraph svelte-1yqlmgk" data-svelte-h="svelte-1ol8fo2">Faites appel à notre agence Web pour la création de votre site internet.
            Autour d&#39;un petit café lors d&#39;un premier rendez-vous gratuit, nous pourrons aborder ensemble toutes les questions que vous vous posez à propos de la création de votre site internet.</p> ${validate_component(ButtonCTA, "ButtonCta").$$render($$result, {}, {}, {})}</div> <div class="wrapper__faqLink">${validate_component(FaqLink, "FaqLink").$$render($$result, {}, {}, {})} <a href="/FAQ" data-svelte-h="svelte-ytks2v">FAQ</a></div> </div>`;
});
export {
  Page as default
};
