import { c as create_ssr_component, v as validate_component, d as add_attribute } from "../../../chunks/ssr.js";
import { H as Header } from "../../../chunks/Header.js";
/* empty css                                                   */
/* empty css                                                     */
/* empty css                                                            */
/* empty css                                                          */
import { F as Form } from "../../../chunks/Form.js";
import { M as Mouse } from "../../../chunks/Mouse.js";
import { B as ButtonCTA } from "../../../chunks/ButtonCTA.js";
import { F as FaqLink } from "../../../chunks/FaqLink.js";
import { L as LinkSiteApplication } from "../../../chunks/LinkSiteApplication.js";
const imgHero = "/_app/immutable/assets/webExplosion.Bgh2rU_O.png";
const design = "/_app/immutable/assets/Design.CGnugKFp.jpg";
const communication = "/_app/immutable/assets/supportCommunication.BSIokpEj.png";
const logoCrea = "/_app/immutable/assets/logoBiere.CkL8vylK.png";
const css = {
  code: ".sites-section.svelte-fp4tad.svelte-fp4tad{display:flex;align-items:center;justify-content:center;flex-direction:column;background-color:rgb(245, 244, 244);height:auto;font-size:16px}.hero.svelte-fp4tad.svelte-fp4tad{display:flex;flex-direction:column;align-items:center;justify-content:center;height:auto}.imgHero.svelte-fp4tad.svelte-fp4tad{max-width:60%;min-width:60%;margin-top:30px}.hero.svelte-fp4tad h1.svelte-fp4tad{text-align:center;font-family:var(--Geologica);font-weight:900;font-weight:900;font-size:2.5rem;color:var(--primary);margin-top:0px;letter-spacing:-2px;padding:15px;line-height:50px;margin-top:40px}.hero.svelte-fp4tad h1 span.svelte-fp4tad{color:var(--green)}.hero.svelte-fp4tad h2.svelte-fp4tad{font-family:poppins;font-weight:300;font-size:var(--m);color:var(--primary);text-align:center;margin-top:50px;margin-bottom:100px;width:80%}.container-service.svelte-fp4tad.svelte-fp4tad{display:flex;flex-direction:column;justify-content:center;align-items:center;margin-top:0px;padding:25px}.container-service.svelte-fp4tad h1.svelte-fp4tad{text-align:center;font-family:'Red Hat Display';font-size:var(--l);font-weight:700;color:var(--primary);margin-top:100px;letter-spacing:-1px}.wrapper-service.svelte-fp4tad.svelte-fp4tad{display:flex;flex-direction:row;justify-content:center;align-items:stretch;gap:10px;margin-top:30px;padding:20px}.wrapper-img.svelte-fp4tad.svelte-fp4tad{display:flex;flex-direction:column;justify-content:center;align-items:center;gap:10px;box-shadow:0px 0px 10px 0px rgba(0, 0, 0, 0.204);border-radius:5px;padding:20px;min-width:35%;max-height:100%}.wrapper-img.svelte-fp4tad h2.svelte-fp4tad{font-family:'Red Hat Display';font-size:var(--m);font-weight:700;color:var(--primary);margin-top:0px;letter-spacing:-1px}.img-design.svelte-fp4tad.svelte-fp4tad{max-width:100%;max-height:50%;margin-top:50px;border-radius:5px}.img-biere.svelte-fp4tad.svelte-fp4tad{max-width:100%;min-height:60%;margin-top:50px;border-radius:5px}.testimonial.svelte-fp4tad.svelte-fp4tad{display:flex;justify-content:center;align-items:center;margin-top:0px;height:auto;background:var(--gradient);padding:0px;gap:0px;width:100%;height:200px}.testimonial.svelte-fp4tad h2.svelte-fp4tad{font-family:'Poppins';font-weight:400;font-size:var(--m);color:white;text-align:center;line-height:30px;letter-spacing:0px;padding:40px}@keyframes svelte-fp4tad-bounce{0%{transform:scale(1) translateY(-2px)}25%{transform:scale(1) translateY(3px)}50%{transform:scale(1) translateY(-1px)}75%{transform:scale(1) translateY(2px)}100%{transform:scale(1) translateY(0)}}@media screen and (max-width: 768px){.wrapper-service.svelte-fp4tad.svelte-fp4tad{display:flex;flex-direction:column;justify-content:center;align-items:stretch;gap:20px;margin-top:30px}.testimonial.svelte-fp4tad.svelte-fp4tad{height:400px}.imgHero.svelte-fp4tad.svelte-fp4tad{min-width:100%;margin-top:30px}}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${validate_component(Mouse, "Mouse").$$render($$result, {}, {}, {})} ${validate_component(Header, "Header").$$render($$result, {}, {}, {})}  <section class="sites-section svelte-fp4tad"><div class="hero svelte-fp4tad"><img${add_attribute("src", imgHero, 0)} alt="" class="imgHero svelte-fp4tad"> <h1 class="svelte-fp4tad" data-svelte-h="svelte-1x2jwbi">Création de <br><span class="svelte-fp4tad">Design, Logos et supports de Com&#39;</span></h1> <h2 class="svelte-fp4tad" data-svelte-h="svelte-giuqyf">L&#39;agence Gralypho crée vos designs Web pour qu&#39;ils soient en parfaite adéquation avec votre
			projet. <br>Le design d&#39;un site ou d&#39;une application, selon plusieurs études menées aupès
			des utilisateurs du Web est essentiel pour plus de 75% des sondés.</h2> ${validate_component(ButtonCTA, "Button").$$render($$result, {}, {}, {})}</div> <div class="container-service svelte-fp4tad" data-svelte-h="svelte-14pfr98"><h1 class="svelte-fp4tad">Étude et réalisation de design sur mesure</h1> <div class="wrapper-service svelte-fp4tad"><div class="wrapper-img svelte-fp4tad"><h2 class="svelte-fp4tad">Design Page Web</h2> <img${add_attribute("src", design, 0)} alt="illustration de différents logo pour apiculteur" class="img-design svelte-fp4tad"></div> <div class="wrapper-img svelte-fp4tad"><h2 class="svelte-fp4tad">Création de logos</h2> <img${add_attribute("src", logoCrea, 0)} alt="illustration de différents logo pour apiculteur" class="img-biere svelte-fp4tad"></div> <div class="wrapper-img svelte-fp4tad"><h2 class="svelte-fp4tad">Création de support de communication</h2> <img${add_attribute("src", communication, 0)} alt="Photos de cartes de visites" class="img-design svelte-fp4tad"></div></div></div> ${validate_component(LinkSiteApplication, "Links").$$render($$result, {}, {}, {})} <div class="wrapper__faqLink">${validate_component(FaqLink, "FaqLink").$$render($$result, {}, {}, {})}</div> <div class="testimonial svelte-fp4tad" data-svelte-h="svelte-1hij7p6"><h2 class="svelte-fp4tad">« Mon but est d’atteindre deux choses : la simplicité et la clarté. <br> Les bons designs naissent
			de ces deux éléments. » – Lindon Leader</h2></div> ${validate_component(Form, "Form").$$render($$result, {}, {}, {})} </section>`;
});
export {
  Page as default
};
