import { c as create_ssr_component, v as validate_component, d as add_attribute } from "../../../chunks/ssr.js";
import { F as FaqLink } from "../../../chunks/FaqLink.js";
import { H as Header } from "../../../chunks/Header.js";
import { L as LinkSiteApplication } from "../../../chunks/LinkSiteApplication.js";
/* empty css                                                      */
const picture = "/_app/immutable/assets/montsDuLyonnais.CxyE18oo.jpeg";
const css = {
  code: ".container.svelte-oef03k{height:100%}.wrapper__text.svelte-oef03k{display:flex;flex-direction:column;justify-content:center;align-items:center;width:80%;margin:0 auto}.title.svelte-oef03k{font-family:var(--Geologica);font-size:var(--l);color:var(--primary);font-weight:900;margin-bottom:10px;letter-spacing:-1px;text-align:center;line-height:35px;margin-top:50px;padding:25px\n	}.subtitle.svelte-oef03k{font-family:var(--Geologica);font-size:1.5rem;color:var(--primary);font-weight:500;letter-spacing:-1px;text-align:center;line-height:40px;margin-top:30px;padding:25px}.subtitle__h3.svelte-oef03k{font-family:var(--Geologica);font-size:var(--m);color:var(--primary);font-weight:700;letter-spacing:-1px;text-align:center;margin-top:50px}.paragraph.svelte-oef03k{font-family:var(--Poppins);font-size:var(--m);color:var(--primary);font-weight:300;letter-spacing:-0.02em;text-align:center;align-self:center;padding:20px}.wrapper__img.svelte-oef03k{display:flex;justify-content:center;align-items:center}.img.svelte-oef03k{height:100%;width:500px;border-radius:20px;margin-top:20px;box-shadow:0px 20px 10px 0px rgba(0, 0, 0, 0.269)}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${validate_component(Header, "Header").$$render($$result, {}, {}, {})} <div class="container svelte-oef03k"><h1 class="title svelte-oef03k" data-svelte-h="svelte-1x32chl">Agence Web des Monts du Lyonnais</h1> <div class="wrapper__img svelte-oef03k" data-svelte-h="svelte-jn0dgl"><img${add_attribute("src", picture, 0)} alt="panorama des monts du Lyonnais" class="img svelte-oef03k"></div> <div class="wrapper__text svelte-oef03k" data-svelte-h="svelte-nb6o6d"><h2 class="subtitle svelte-oef03k">Les acteurs tech de la région de l&#39;ouest Lyonnais</h2> <h3 class="subtitle__h3 svelte-oef03k">À 15 km de Lyon, un vivier de pépites.</h3> <p class="paragraph svelte-oef03k">Avec des ZA accueillant des entreprises de renom, les monts du Lyonnais constituent un territoire dynamique et innovant, à moins de 15 km de Lyon. <br>Le cadre verdoyant et préservé attire de nombreux visiteurs et si l&#39;authenticité des monts attire, la qualité des prestations des acteurs tech de la région est également un atout majeur.
        Gralypho, agence web implantée au coeur des monts du Lyonnais, a choisi de s&#39;implanter dans cette région pour couvrir les besoins digitaux des entreprises locales, celles de Lyon, ainsi que celles de la région Lyonnaise.</p> <h3 class="subtitle__h3 svelte-oef03k">Un territoire stratégique</h3> <p class="paragraph svelte-oef03k">Les monts du Lyonnais sont enclavés à l&#39;ouest de Lyon entre les monts du beaujolais, les monts du Forez et le pilat. Aux portes de la Loire, à la fois proche de l&#39;A7 et de l&#39;A42, pour l&#39;agence Web Gralypho, l&#39;implantation dans les monts du Lyonnais est une stratégie gagnante.</p>  <h2 class="subtitle svelte-oef03k">Un choix 100% gagnant</h2> <p class="paragraph svelte-oef03k">Alliant cadre verdoyant, authentique et préservé, il fait bon vivre et travailler dans les monts du Lyonnais. Nous bénéficions d&#39;un confort de travail optimal tout en étant à moins de trente minutes de Lyon, ce qui nous permet de répondre aux besoins digitaux des entreprises des monts du Lyonnais, de Lyon et de la région Lyonnaise. Pour Gralypho, agence Web, c&#39;est un choix 100% gagnant !</p></div> ${validate_component(LinkSiteApplication, "Links").$$render($$result, {}, {}, {})} <div class="wrapper__faqLink">${validate_component(FaqLink, "FaqLink").$$render($$result, {}, {}, {})} <a href="/FAQ" data-svelte-h="svelte-ytks2v">FAQ</a></div> </div>`;
});
export {
  Page as default
};
