import { c as create_ssr_component, e as escape, d as add_attribute } from "../../../../chunks/ssr.js";
const css = {
  code: "article.svelte-wtup6b.svelte-wtup6b{font-family:var(--Red);max-width:800px;margin:0 auto;padding:20px;background-color:#f9f9f9;border-radius:8px;box-shadow:0 2px 4px rgba(0, 0, 0, 0.1);height:100%}article.svelte-wtup6b h1.svelte-wtup6b{font-size:2rem;margin-bottom:10px}article.svelte-wtup6b p.svelte-wtup6b{font-size:1rem;color:#555}article.svelte-wtup6b div.svelte-wtup6b{font-size:1rem;line-height:1.6;color:#334}article.svelte-wtup6b em.svelte-wtup6b{font-style:italic;color:#888}img.svelte-wtup6b.svelte-wtup6b{max-width:100%;height:auto;border-radius:1rem;box-shadow:0 4px 12px rgba(0, 0, 0, 0.15);margin:1rem 0}",
  map: '{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<script>\\n\\texport let data;\\n\\tconst { article } = data;\\n<\/script>\\n\\n<svelte:head>\\n\\t<title>{article.title}</title>\\n\\t<meta name=\\"description\\" content={article.description} />\\n\\t<meta property=\\"og:title\\" content={article.title} />\\n\\t<meta property=\\"og:description\\" content={article.description} />\\n\\t<meta property=\\"og:image\\" content={article.image} />\\n\\t<meta property=\\"og:url\\" content={`https://gralypho.com//blog/${article.slug}`} />\\n\\t<meta property=\\"og:type\\" content=\\"article\\" />\\n</svelte:head>\\n\\n{#if article}\\n\\t<article class=\\"article-content\\">\\n\\t\\t<h1>{article.title}</h1>\\n\\t\\t<p><em>{article.date}</em></p>\\n\\t\\t{#if article.image}\\n\\t\\t\\t<img src={article.image} alt=\\"Illustration pour {article.title}\\" class=\\"featured-image\\" />\\n\\t\\t{/if}\\n\\t\\t<div>{@html article.content}</div>\\n\\t</article>\\n{:else}\\n\\t<p>Article introuvable.</p>\\n{/if}\\n\\n<style>\\n\\tarticle {\\n\\t\\tfont-family: var(--Red);\\n\\t\\tmax-width: 800px;\\n\\t\\tmargin: 0 auto;\\n\\t\\tpadding: 20px;\\n\\t\\tbackground-color: #f9f9f9;\\n\\t\\tborder-radius: 8px;\\n\\t\\tbox-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\\n\\t\\theight: 100%;\\n\\t}\\n\\tarticle h1 {\\n\\t\\tfont-size: 2rem;\\n\\t\\tmargin-bottom: 10px;\\n\\t}\\n\\tarticle p  {\\n\\t\\tfont-size: 1rem;\\n\\t\\tcolor: #555;\\n\\t}\\n\\tarticle div {\\n\\t\\tfont-size: 1rem;\\n\\t\\tline-height: 1.6;\\n\\t\\tcolor: #334;\\n\\t}\\n\\tarticle em {\\n\\t\\tfont-style: italic;\\n\\t\\tcolor: #888;\\n\\t}\\n\\timg {\\n\\t\\tmax-width: 100%;\\n\\t\\theight: auto;\\n\\t\\tborder-radius: 1rem;\\n\\t\\tbox-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);\\n\\t\\tmargin: 1rem 0;\\n\\t}\\n</style>\\n"],"names":[],"mappings":"AA6BC,mCAAQ,CACP,WAAW,CAAE,IAAI,KAAK,CAAC,CACvB,SAAS,CAAE,KAAK,CAChB,MAAM,CAAE,CAAC,CAAC,IAAI,CACd,OAAO,CAAE,IAAI,CACb,gBAAgB,CAAE,OAAO,CACzB,aAAa,CAAE,GAAG,CAClB,UAAU,CAAE,CAAC,CAAC,GAAG,CAAC,GAAG,CAAC,KAAK,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,GAAG,CAAC,CACxC,MAAM,CAAE,IACT,CACA,qBAAO,CAAC,gBAAG,CACV,SAAS,CAAE,IAAI,CACf,aAAa,CAAE,IAChB,CACA,qBAAO,CAAC,eAAG,CACV,SAAS,CAAE,IAAI,CACf,KAAK,CAAE,IACR,CACA,qBAAO,CAAC,iBAAI,CACX,SAAS,CAAE,IAAI,CACf,WAAW,CAAE,GAAG,CAChB,KAAK,CAAE,IACR,CACA,qBAAO,CAAC,gBAAG,CACV,UAAU,CAAE,MAAM,CAClB,KAAK,CAAE,IACR,CACA,+BAAI,CACH,SAAS,CAAE,IAAI,CACf,MAAM,CAAE,IAAI,CACZ,aAAa,CAAE,IAAI,CACnB,UAAU,CAAE,CAAC,CAAC,GAAG,CAAC,IAAI,CAAC,KAAK,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,IAAI,CAAC,CAC1C,MAAM,CAAE,IAAI,CAAC,CACd"}'
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { data } = $$props;
  const { article } = data;
  if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-516gt9_START -->${$$result.title = `<title>${escape(article.title)}</title>`, ""}<meta name="description"${add_attribute("content", article.description, 0)}><meta property="og:title"${add_attribute("content", article.title, 0)}><meta property="og:description"${add_attribute("content", article.description, 0)}><meta property="og:image"${add_attribute("content", article.image, 0)}><meta property="og:url"${add_attribute("content", `https://gralypho.com//blog/${article.slug}`, 0)}><meta property="og:type" content="article"><!-- HEAD_svelte-516gt9_END -->`, ""} ${article ? `<article class="article-content svelte-wtup6b"><h1 class="svelte-wtup6b">${escape(article.title)}</h1> <p class="svelte-wtup6b"><em class="svelte-wtup6b">${escape(article.date)}</em></p> ${article.image ? `<img${add_attribute("src", article.image, 0)} alt="${"Illustration pour " + escape(article.title, true)}" class="featured-image svelte-wtup6b">` : ``} <div class="svelte-wtup6b"><!-- HTML_TAG_START -->${article.content}<!-- HTML_TAG_END --></div></article>` : `<p data-svelte-h="svelte-n3u3rp">Article introuvable.</p>`}`;
});
export {
  Page as default
};
