import { c as create_ssr_component, v as validate_component, d as add_attribute } from "../../../chunks/ssr.js";
import { H as Header } from "../../../chunks/Mouse.svelte_svelte_type_style_lang.js";
import { M as Mouse } from "../../../chunks/Mouse.js";
import { B as ButtonCTA } from "../../../chunks/ButtonCTA.js";
const digital = "/_app/immutable/assets/23.B1lRdX8y.png";
const css = {
  code: ".digital-infos.svelte-1xjakut.svelte-1xjakut{display:flex;justify-content:center;align-items:center;gap:0px;height:auto}.container.svelte-1xjakut.svelte-1xjakut{display:flex;justify-content:center;align-items:center;flex-direction:column}.container.svelte-1xjakut>.svelte-1xjakut{flex-basis:50%}.digital-infos.svelte-1xjakut img.svelte-1xjakut{width:70%;height:auto}.wrapper-digital-infos.svelte-1xjakut.svelte-1xjakut{display:flex;flex-direction:column;justify-content:center;align-items:center;gap:20px;padding:20px;color:var(--textHero);margin-top:30px;height:auto;width:90%}.wrapper-digital-infos.svelte-1xjakut h1.svelte-1xjakut{font-size:1.8em;font-weight:700;text-align:center;font-family:var(--Radio);letter-spacing:-0.5px}.wrapper-digital-infos.svelte-1xjakut h3.svelte-1xjakut{font-family:var(--Radio);font-size:var(--l);font-weight:700;text-align:center;color:var(--green);margin-top:15px}.wrapper-digital-infos.svelte-1xjakut p.svelte-1xjakut{font-family:var(--Radio);font-size:var(--m);font-weight:400;text-align:center;padding:20px;line-height:30px}.wrapper-digital-infos.svelte-1xjakut p span.svelte-1xjakut{font-weight:700}.wrapper-button.svelte-1xjakut.svelte-1xjakut{display:flex;justify-content:center;align-items:center;margin-top:30px;margin-bottom:50px}@media screen and (max-width: 768px){.wrapper-digital-infos.svelte-1xjakut.svelte-1xjakut{width:100%}}.digital-infos.svelte-1xjakut img.svelte-1xjakut{width:100%}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${validate_component(Mouse, "Mouse").$$render($$result, {}, {}, {})} ${validate_component(Header, "Header").$$render($$result, {}, {}, {})} <section class="digital-infos svelte-1xjakut"><div class="container svelte-1xjakut"><img${add_attribute("src", digital, 0)} alt="" class="svelte-1xjakut"> <div class="wrapper-digital-infos svelte-1xjakut" data-svelte-h="svelte-14zpo63"><h3 class="svelte-1xjakut">Un site Web, mais pour quoi faire?</h3> <h1 class="svelte-1xjakut">Profitez de votre outil Digital, en découvrant tout ce qu&#39;il peut vous apporter !</h1> <p class="svelte-1xjakut">Un site internet c&#39;est en fait un outil très puissant. Un outil que nous allons paramétrer, que nous allons élaborer pour qu&#39;il puisse faire ce que vous souhaitez: <br> Convertir de nouveaux clients, vendre des produits, proposez un service, analyser des marchés, des tendances, gérer vos stocks, vos clients, etc..  <br><br>Votre site internet ou votre application sera en ligne 24/7. Autrement dit, ce sera une hyper présence dont il faut absolument profiter. C&#39;est du temps économisé . Du temps pendant lequel votre site travaille pour vous, vend pour vous, attire de nouveaux clients pour vous, prend des rendez-vous pour vous, présente vos produits pour vous, vos services., etc. <br><br>
                Déterminer ce que fera votre outil digital est primordial, essentiel. Tout dépend de la stratégie que nous définirons ensemble, pour que votre outil vous permette d&#39;atteindre <span class="svelte-1xjakut">votre objectif.</span></p></div> <div class="wrapper-button svelte-1xjakut">${validate_component(ButtonCTA, "Button").$$render($$result, {}, {}, {})}</div></div> </section>`;
});
export {
  Page as default
};
