[build]
    command = "npm run build"
    publish = "build/"
    functions = "functions/"



    [[redirects]]
  from = "/marketing"
  to = "/creation-logos-publicite-communication-thurins-web"
  status = 301
  force = true

[[redirects]]
  from = "/referencement"
  to = "/Referencement-seo-sea-thurins-web"
  status = 301
  force = true

[[redirects]]
  from = "/refonte"
  to = "/Medias-sociaux-thurins-web"
  status = 301
  force = true

[[redirects]]
  from = "/applications"
  to = "/creation-application-web-lyon"
  status = 301
  force = true

[[redirects]]
  from = "/Site-infos"
  to = "/Design-site-web-thurins#wrapper-design"
  status = 301
  force = true

[[redirects]]
  from = "/Composants"
  to = "/strategie-communication-web"
  status = 301
  force = true

[[redirects]]
  from = "/Refonte"
  to = "/Tarifs-creation-site-web-lyon"
  status = 301
  force = true

[[redirects]]
  from = "/Sites"
  to = "/creation-site-web-lyon"
  status = 301
  force = true

[[redirects]]
  from = "/Sites-description"
  to = "/creation-site-web-ouest-lyonnais"
  status = 301
  force = true
