import { c as create_ssr_component } from "./ssr.js";
/* empty css                                        */
const css = {
  code: "a.svelte-93e84g{background-color:var(--green);color:var(--primary);font-family:'Red Hat Display';font-size:1rem;font-weight:700;border-radius:8px;text-align:center;padding:10px 20px;box-shadow:0px 10px 10px rgba(62, 62, 62, 0.5);z-index:999;max-width:100px}a.svelte-93e84g:hover{animation:svelte-93e84g-bounce 0.4s ease-in-out}@keyframes svelte-93e84g-bounce{0%{transform:scale(1) translateY(-2px)}25%{transform:scale(1) translateY(3px)}50%{transform:scale(1) translateY(-1px)}75%{transform:scale(1) translateY(2px)}100%{transform:scale(1) translateY(0)}}",
  map: `{"version":3,"file":"ButtonCTA.svelte","sources":["ButtonCTA.svelte"],"sourcesContent":["<a  href=\\"/#section-form\\">Contact</a>\\n\\n<style>\\n\\ta {\\n\\t\\tbackground-color: var(--green);\\n\\t\\tcolor:  var(--primary);\\n\\t\\tfont-family: 'Red Hat Display';\\n\\t\\tfont-size: 1rem;\\n\\t\\tfont-weight: 700;\\n\\t\\tborder-radius: 8px;\\n\\t\\ttext-align: center;\\n\\t\\tpadding: 10px 20px;\\n\\t\\tbox-shadow: 0px 10px 10px rgba(62, 62, 62, 0.5);\\n\\t\\tz-index: 999;\\n\\t\\tmax-width: 100px;\\n \\n\\t}\\n        a:hover{\\n                animation: bounce 0.4s ease-in-out;\\n        }\\n        \\t@keyframes bounce {\\n\\t\\t0% {\\n\\t\\t\\ttransform: scale(1) translateY(-2px);\\n\\t\\t}\\n\\t\\t25% {\\n\\t\\t\\ttransform: scale(1) translateY(3px);\\n\\t\\t}\\n\\t\\t50% {\\n\\t\\t\\ttransform: scale(1) translateY(-1px);\\n\\t\\t}\\n\\t\\t75% {\\n\\t\\t\\ttransform: scale(1) translateY(2px);\\n\\t\\t}\\n\\t\\t100% {\\n\\t\\t\\ttransform: scale(1) translateY(0);\\n\\t\\t}\\n\\t}\\n\\n</style>\\n"],"names":[],"mappings":"AAGC,eAAE,CACD,gBAAgB,CAAE,IAAI,OAAO,CAAC,CAC9B,KAAK,CAAG,IAAI,SAAS,CAAC,CACtB,WAAW,CAAE,iBAAiB,CAC9B,SAAS,CAAE,IAAI,CACf,WAAW,CAAE,GAAG,CAChB,aAAa,CAAE,GAAG,CAClB,UAAU,CAAE,MAAM,CAClB,OAAO,CAAE,IAAI,CAAC,IAAI,CAClB,UAAU,CAAE,GAAG,CAAC,IAAI,CAAC,IAAI,CAAC,KAAK,EAAE,CAAC,CAAC,EAAE,CAAC,CAAC,EAAE,CAAC,CAAC,GAAG,CAAC,CAC/C,OAAO,CAAE,GAAG,CACZ,SAAS,CAAE,KAEZ,CACO,eAAC,MAAM,CACC,SAAS,CAAE,oBAAM,CAAC,IAAI,CAAC,WAC/B,CACC,WAAW,oBAAO,CACzB,EAAG,CACF,SAAS,CAAE,MAAM,CAAC,CAAC,CAAC,WAAW,IAAI,CACpC,CACA,GAAI,CACH,SAAS,CAAE,MAAM,CAAC,CAAC,CAAC,WAAW,GAAG,CACnC,CACA,GAAI,CACH,SAAS,CAAE,MAAM,CAAC,CAAC,CAAC,WAAW,IAAI,CACpC,CACA,GAAI,CACH,SAAS,CAAE,MAAM,CAAC,CAAC,CAAC,WAAW,GAAG,CACnC,CACA,IAAK,CACJ,SAAS,CAAE,MAAM,CAAC,CAAC,CAAC,WAAW,CAAC,CACjC,CACD"}`
};
const ButtonCTA = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<a href="/#section-form" class="svelte-93e84g" data-svelte-h="svelte-bhywgi">Contact</a>`;
});
export {
  ButtonCTA as B
};
