import { c as create_ssr_component, d as add_attribute } from "./ssr.js";
const gralypho = "/_app/immutable/assets/logoGralypho.CI6Sh97R.jpeg";
const css = {
  code: ".logo.svelte-1vzsicl{width:50px;height:50px;border-radius:8px}.rect.svelte-1vzsicl{display:flex;gap:0px;min-width:20%;height:40px;font-weight:600;justify-content:center;align-items:center;border-radius:5px;margin-left:0px}.title.svelte-1vzsicl{font-family:var(--Poppins);font-size:0.8rem;color:var(--whiteGrey);margin-top:0px;font-weight:600;letter-spacing:-1px;margin-left:5px}.rect.svelte-1vzsicl:hover{animation:svelte-1vzsicl-bounce 0.4s ease-in-out}@keyframes svelte-1vzsicl-bounce{0%{transform:scale(1) translateY(-2px)}25%{transform:scale(1) translateY(3px)}50%{transform:scale(1) translateY(-1px)}75%{transform:scale(1) translateY(2px)}100%{transform:scale(1) translateY(0)}}",
  map: `{"version":3,"file":"Gralypho.svelte","sources":["Gralypho.svelte"],"sourcesContent":["<script>\\n\\timport gralypho from '../Assets/logoGralypho.jpeg';\\n<\/script>\\n\\n<div class=\\"rect\\">\\n\\t\\n\\t<img class=\\"logo\\" src={gralypho} alt=\\"logo de Gralypho\\" />\\n\\t<h1 class=\\"title\\">Gralypho</h1>\\n</div>\\n\\n<style>\\n\\t.logo {\\n\\t\\twidth: 50px;\\n\\t\\theight: 50px;\\n\\t\\tborder-radius: 8px;\\n\\t}\\n\\t.rect {\\n\\t\\tdisplay: flex;\\n\\t\\tgap: 0px;\\n\\t\\tmin-width: 20%;\\n\\t\\theight: 40px;\\n\\t\\tfont-weight: 600;\\n\\t\\tjustify-content: center;\\n\\t\\talign-items: center;\\n\\t\\tborder-radius: 5px;\\n\\t\\tmargin-left: 0px;\\n\\t}\\n\\t.title {\\n\\t\\tfont-family: var(--Poppins);\\n\\t\\tfont-size: 0.8rem;\\n\\t\\tcolor: var(--whiteGrey);\\n\\t\\tmargin-top: 0px;\\n\\t\\tfont-weight: 600;\\n\\t\\tletter-spacing: -1px;\\n\\t\\tmargin-left: 5px;\\n\\t}\\n\\n\\t.rect:hover {\\n\\t\\tanimation: bounce 0.4s ease-in-out;\\n\\t}\\n\\n\\t@keyframes bounce {\\n\\t\\t0% {\\n\\t\\t\\ttransform: scale(1) translateY(-2px);\\n\\t\\t}\\n\\t\\t25% {\\n\\t\\t\\ttransform: scale(1) translateY(3px);\\n\\t\\t}\\n\\t\\t50% {\\n\\t\\t\\ttransform: scale(1) translateY(-1px);\\n\\t\\t}\\n\\t\\t75% {\\n\\t\\t\\ttransform: scale(1) translateY(2px);\\n\\t\\t}\\n\\t\\t100% {\\n\\t\\t\\ttransform: scale(1) translateY(0);\\n\\t\\t}\\n\\t}\\n</style>\\n"],"names":[],"mappings":"AAWC,oBAAM,CACL,KAAK,CAAE,IAAI,CACX,MAAM,CAAE,IAAI,CACZ,aAAa,CAAE,GAChB,CACA,oBAAM,CACL,OAAO,CAAE,IAAI,CACb,GAAG,CAAE,GAAG,CACR,SAAS,CAAE,GAAG,CACd,MAAM,CAAE,IAAI,CACZ,WAAW,CAAE,GAAG,CAChB,eAAe,CAAE,MAAM,CACvB,WAAW,CAAE,MAAM,CACnB,aAAa,CAAE,GAAG,CAClB,WAAW,CAAE,GACd,CACA,qBAAO,CACN,WAAW,CAAE,IAAI,SAAS,CAAC,CAC3B,SAAS,CAAE,MAAM,CACjB,KAAK,CAAE,IAAI,WAAW,CAAC,CACvB,UAAU,CAAE,GAAG,CACf,WAAW,CAAE,GAAG,CAChB,cAAc,CAAE,IAAI,CACpB,WAAW,CAAE,GACd,CAEA,oBAAK,MAAO,CACX,SAAS,CAAE,qBAAM,CAAC,IAAI,CAAC,WACxB,CAEA,WAAW,qBAAO,CACjB,EAAG,CACF,SAAS,CAAE,MAAM,CAAC,CAAC,CAAC,WAAW,IAAI,CACpC,CACA,GAAI,CACH,SAAS,CAAE,MAAM,CAAC,CAAC,CAAC,WAAW,GAAG,CACnC,CACA,GAAI,CACH,SAAS,CAAE,MAAM,CAAC,CAAC,CAAC,WAAW,IAAI,CACpC,CACA,GAAI,CACH,SAAS,CAAE,MAAM,CAAC,CAAC,CAAC,WAAW,GAAG,CACnC,CACA,IAAK,CACJ,SAAS,CAAE,MAAM,CAAC,CAAC,CAAC,WAAW,CAAC,CACjC,CACD"}`
};
const Gralypho = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<div class="rect svelte-1vzsicl" data-svelte-h="svelte-1bgfxj9"><img class="logo svelte-1vzsicl"${add_attribute("src", gralypho, 0)} alt="logo de Gralypho"> <h1 class="title svelte-1vzsicl">Gralypho</h1> </div>`;
});
export {
  Gralypho as G
};
