import { c as create_ssr_component, v as validate_component, e as escape } from "./ssr.js";
import { G as Gralypho } from "./Gralypho.js";
const css = {
  code: ".navigation.svelte-1fq733b.svelte-1fq733b{grid-template-columns:repeat(12, 1fr);grid-template-rows:auto;width:100%;display:flex;flex-direction:column;padding:10px;font-size:16px;background-color:transparent;background-color:var(--primary);border-bottom:1px solid rgba(128, 128, 128, 0.278);z-index:2}.container__header.svelte-1fq733b.svelte-1fq733b{display:flex;flex-direction:row;align-items:center;justify-content:space-between}.form.svelte-1fq733b.svelte-1fq733b{background-color:var(--cta)}.navigation.svelte-1fq733b h1 span.svelte-1fq733b{color:rgb(236, 228, 228);font-weight:900}.wrapper-logo-burger.svelte-1fq733b.svelte-1fq733b{display:flex;flex-direction:row;align-items:center;justify-content:center;z-index:3;gap:10px}.contact.svelte-1fq733b.svelte-1fq733b{border:1px solid var(--whiteGrey);padding:10px 20px;border-radius:20px;color:white;font-family:var(--Red)}.contact.svelte-1fq733b.svelte-1fq733b:hover{background-color:var(--whiteGrey);color:var(--primary)}.contact.svelte-1fq733b.svelte-1fq733b:active{background-color:var(--primary);color:var(--whiteGrey)}.logo.svelte-1fq733b.svelte-1fq733b{grid-column:2;grid-row:1;display:flex;flex-direction:column;justify-content:center;align-items:center;margin-top:10px;margin-bottom:5px;margin-left:20px}.span.svelte-1fq733b.svelte-1fq733b{grid-column:2/12;grid-row:2;display:flex;justify-content:center;align-items:center}.wrapper-links.svelte-1fq733b.svelte-1fq733b{display:flex;align-items:center;justify-content:center;gap:26px;opacity:1;margin-top:50px;margin-bottom:40px;z-index:2}.link-contact.svelte-1fq733b.svelte-1fq733b{color:var(--whiteGrey);font-size:1em;font-weight:400;text-decoration:none;transition:0.4s ease-in-out;z-index:2;font-family:'Red Hat Display'}a.svelte-1fq733b.svelte-1fq733b:hover{transition:0.4s ease-in-out;color:grey}.burger-menu.svelte-1fq733b.svelte-1fq733b{background-color:transparent;border:none;grid-column:6;grid-row:1;padding:10px;z-index:4;margin-right:5px;z-index:100}.burger-menu.svelte-1fq733b.svelte-1fq733b:hover{animation:svelte-1fq733b-bounce 0.4s ease-in-out}.burger.svelte-1fq733b.svelte-1fq733b{font-size:2em;border:none;color:var(--whiteGrey);border-radius:50%;padding:14px;max-width:100px;max-height:70px;z-index:4}.burger.svelte-1fq733b.svelte-1fq733b:hover{animation:svelte-1fq733b-bounce 0.4s ease-in-out}@keyframes svelte-1fq733b-bounce{0%{transform:scale(1) translateY(-2px)}25%{transform:scale(1) translateY(3px)}50%{transform:scale(1) translateY(-1px)}75%{transform:scale(1) translateY(2px)}100%{transform:scale(1) translateY(0)}}@media screen and (max-width: 1042px){.wrapper-links.svelte-1fq733b.svelte-1fq733b{flex-direction:column;justify-content:center;align-items:center;gap:10px}.navigation.svelte-1fq733b.svelte-1fq733b{font-size:16px}.link-contact.svelte-1fq733b.svelte-1fq733b{font-size:1.1em}.burger-menu.svelte-1fq733b.svelte-1fq733b{z-index:2}.contact.svelte-1fq733b.svelte-1fq733b{display:none}}",
  map: null
};
const Header = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<nav class="navigation svelte-1fq733b"><div class="container__header svelte-1fq733b"><a href="/" class="logo svelte-1fq733b">${validate_component(Gralypho, "Logo").$$render($$result, {}, {}, {})}</a> <div class="wrapper-logo-burger svelte-1fq733b"><a class="contact form svelte-1fq733b" href="/#section-form" data-svelte-h="svelte-1a0vwwf">Nous contacter</a> <a class="contact svelte-1fq733b" href="tel:+33672901614" type="telephone" data-svelte-h="svelte-63gsks">06 72 90 16 14</a> <button class="burger-menu svelte-1fq733b" aria-label="Menu"><i class="${"fa-solid fa-bars burger " + escape("", true) + " svelte-1fq733b"}"></i></button></div></div> ${``} </nav>`;
});
export {
  Header as H
};
