import { c as create_ssr_component } from "./ssr.js";
const css = {
  code: "a.svelte-ra3tlp{font-family:var(--Geologica);font-size:var(--m);color:var(--whiteGrey);background-color:var(--primary);font-weight:700;letter-spacing:-1px;text-align:center;margin-top:0px;padding:25px;border-radius:8px;box-shadow:0px 30px 20px rgba(0, 0, 0, 0.227)}.bg-color.svelte-ra3tlp{background-color:var(--cta)}a.svelte-ra3tlp:hover{background-color:var(--blue)}.wrapper__links.svelte-ra3tlp{display:flex;gap:20px;justify-content:center;align-items:center;width:80%;margin:0 auto;margin-bottom:50px}.title.svelte-ra3tlp{font-family:var(--Geologica);font-size:var(--l);color:var(--primary);font-weight:900;margin-bottom:10px;letter-spacing:-1px;text-align:center;line-height:35px;margin-top:50px;padding:25px\n    }@media screen and (max-width: 768px){.wrapper__links.svelte-ra3tlp{flex-direction:column}}",
  map: `{"version":3,"file":"LinkSiteApplication.svelte","sources":["LinkSiteApplication.svelte"],"sourcesContent":["<h2 class=\\"title\\">Découvrez notre offre</h2>\\n<div class=\\"wrapper__links\\">\\n\\t<a href=\\"/creation-site-internet\\">Notre offre de site internet</a>\\n\\t<a class=\\"bg-color\\" href=\\"/creation-application\\">Notre offre d'application</a>\\n</div>\\n\\n<style>\\n\\ta {\\n\\t\\tfont-family: var(--Geologica);\\n\\t\\tfont-size: var(--m);\\n\\t\\tcolor: var(--whiteGrey);\\n\\t\\tbackground-color: var(--primary);\\n\\t\\tfont-weight: 700;\\n\\t\\tletter-spacing: -1px;\\n\\t\\ttext-align: center;\\n\\t\\tmargin-top: 0px;\\n\\t\\tpadding: 25px;\\n\\t\\tborder-radius: 8px;\\n\\t\\tbox-shadow: 0px 30px 20px rgba(0, 0, 0, 0.227);\\n\\t}\\n\\t.bg-color {\\n\\t\\tbackground-color: var(--cta);\\n\\t}\\n\\ta:hover {\\n\\t\\tbackground-color: var(--blue);\\n\\t}\\n\\t.wrapper__links {\\n\\t\\tdisplay: flex;\\n\\t\\tgap: 20px;\\n\\t\\tjustify-content: center;\\n\\t\\talign-items: center;\\n\\t\\twidth: 80%;\\n\\t\\tmargin: 0 auto;\\n\\t\\tmargin-bottom: 50px;\\n\\t}\\n    .title{\\n        font-family: var(--Geologica);\\n        font-size: var(--l);\\n        color: var(--primary);\\n        font-weight: 900;\\n        margin-bottom: 10px;\\n        letter-spacing: -1px;\\n        text-align: center;\\n        line-height: 35px;\\n        margin-top: 50px;\\n        padding: 25px\\n    }\\n\\n\\t@media screen and (max-width: 768px) {\\n\\t\\t.wrapper__links {\\n\\t\\t\\tflex-direction: column;\\n\\t\\t}\\n\\t}\\n</style>\\n"],"names":[],"mappings":"AAOC,eAAE,CACD,WAAW,CAAE,IAAI,WAAW,CAAC,CAC7B,SAAS,CAAE,IAAI,GAAG,CAAC,CACnB,KAAK,CAAE,IAAI,WAAW,CAAC,CACvB,gBAAgB,CAAE,IAAI,SAAS,CAAC,CAChC,WAAW,CAAE,GAAG,CAChB,cAAc,CAAE,IAAI,CACpB,UAAU,CAAE,MAAM,CAClB,UAAU,CAAE,GAAG,CACf,OAAO,CAAE,IAAI,CACb,aAAa,CAAE,GAAG,CAClB,UAAU,CAAE,GAAG,CAAC,IAAI,CAAC,IAAI,CAAC,KAAK,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,KAAK,CAC9C,CACA,uBAAU,CACT,gBAAgB,CAAE,IAAI,KAAK,CAC5B,CACA,eAAC,MAAO,CACP,gBAAgB,CAAE,IAAI,MAAM,CAC7B,CACA,6BAAgB,CACf,OAAO,CAAE,IAAI,CACb,GAAG,CAAE,IAAI,CACT,eAAe,CAAE,MAAM,CACvB,WAAW,CAAE,MAAM,CACnB,KAAK,CAAE,GAAG,CACV,MAAM,CAAE,CAAC,CAAC,IAAI,CACd,aAAa,CAAE,IAChB,CACG,oBAAM,CACF,WAAW,CAAE,IAAI,WAAW,CAAC,CAC7B,SAAS,CAAE,IAAI,GAAG,CAAC,CACnB,KAAK,CAAE,IAAI,SAAS,CAAC,CACrB,WAAW,CAAE,GAAG,CAChB,aAAa,CAAE,IAAI,CACnB,cAAc,CAAE,IAAI,CACpB,UAAU,CAAE,MAAM,CAClB,WAAW,CAAE,IAAI,CACjB,UAAU,CAAE,IAAI,CAChB,OAAO,CAAE;AACjB,IAAI,CAEH,OAAO,MAAM,CAAC,GAAG,CAAC,YAAY,KAAK,CAAE,CACpC,6BAAgB,CACf,cAAc,CAAE,MACjB,CACD"}`
};
const LinkSiteApplication = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<h2 class="title svelte-ra3tlp" data-svelte-h="svelte-1cwpqe2">Découvrez notre offre</h2> <div class="wrapper__links svelte-ra3tlp" data-svelte-h="svelte-g4gbxg"><a href="/creation-site-internet" class="svelte-ra3tlp">Notre offre de site internet</a> <a class="bg-color svelte-ra3tlp" href="/creation-application">Notre offre d&#39;application</a> </div>`;
});
export {
  LinkSiteApplication as L
};
